### ISSUE TITLE
Praca Domowa nr 2

### ISSUE THREAD

**Issue by maksymiuks** [mini-pw/2021L-WB-XAI-2#31]
Praca domowa 2 (8 pkt.)
Termin: 07.04.2021 23:59

Dla wybranego modelu przygotuj knitr/jupyter notebook w formacie html lub pdf rozwiązując poniższe punkty. Pracę domową należy zgłosić przez Pull Request na GitHub w folderze PraceDomowe/PracaDomowa2/Nazwisko_Imię.

- Dla wybranej obserwacji ze zbioru danych wylicz predykcję modelu.
- Dla wybranej obserwacji z punktu 1., wylicz dekompozycję predykcji modelu używając LIME (pakiety w R: live, lime, localModel, iml, pakiety w Python: lime, dalex).
- Porównaj dekompozycję LIME dla różnych obserwacji w zbiorze. Jak stabilne są otrzymane wyjaśnienia?
- Skomentuj poszczególne wyniki uzyskane w powyższych punktach.
- Dla wybranej obserwacji porównaj wyjaśnienie LIME wyjaśnieniem BreakDown lub SHAP
- W pracy domowej oceniane przede wszystkim będą wnioski z otrzymanych analiz. Kod potrzebny do reprudokowalności wyników również proszę załączyć.

Prace domowe należy zgłaszać przez Pull Request o tytule Nazwisko Imię PD2. Wszystkie pliki związane z pracą domową proszę o umieszczenie w folderze Nazwisko_Imię.

**Comment by HeroOfElFacil** [comment]
Ze zbiorami jest dowolność, czy robimy po prostu na projektowym?
