### ISSUE TITLE
Praca domowa nr 1

### ISSUE THREAD

**Issue by maksymiuks** [mini-pw/2021L-WB-XAI-2#6]
Praca domowa 1 (8 pkt.)
Termin: 25.03.2021 (przed zajęciami)

Dla wybranego modelu z projektu przygotuj knitr/jupyter notebook w formacie html lub pdf rozwiązując poniższe punkty.

- Dla wybranej obserwacji ze zbioru danych wylicz predykcję modelu.
- Dla wybranej obserwacji z punktu 1., wylicz dekompozycję predykcji modelu używając SHAP, Break Down lub obie (pakiety w R: DALEX, iml, pakiety w Python: shap, dalex, piBreakDown).
- Wybierz dwie obserwacje ze zbioru danych, które mają inne najważniejsze zmienne (na przykład: dla obserwacji A ważne zmienne to wiek i płeć, a dla obserwacji B klasa i rasa).
- Znajdź dwie obserwacje ze zbioru danych, które mają dla tych samych zmiennych inne efekty (pozytywny i negatywny).
- Skomentuj poszczególne wyniki uzyskane w powyższych punktach.

W pracy domowej oceniane przede wszystkim będą wnioski z otrzymanych analiz. Kod potrzebny do reprodukowalności wyników również proszę załączyć.

Prace domowe należy zgłaszać przez Pull Request o tytule Nazwisko Imię PD1. Wszystkie pliki związane z pracą domową proszę o umieszczenie w folderze PraceDomowe/PracaDomowa1/Nazwisko_Imię.

**Comment by jaszczukp** [comment]
Czy pojawi się folder PraceDomowe?
